version: '2.1'

services:
  terceiras-user-client:
    image: terceiras-user-client
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js